### ISSUE TITLE
Method validatePswStrong does not exist.

### ISSUE THREAD

**Issue by visualight** [andrey-helldar/strong-password#6]
Hi,

Cannot validate via FormRequest => Validator :: validatePswStrong does not exist.

What should I do ?

Laravel 7.30.4
Composer Discovered Package: andrey-helldar/strong-password

```
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ChangePassword extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = [
            'new_password' => ['required', 'psw_strong'],
            'new_password_confirmation' => 'required|same:new_password',
        ];

        return $rules;
    }
```

<img width="1218" alt="Capture d’écran 2021-06-28 à 12 12 31" src="https://user-images.githubusercontent.com/3457651/123620131-2d869780-d80a-11eb-8b33-334c0124db92.png">

**Comment by visualight** [comment]
Auto-discover not working. I must add manually 
`$this->app->register(\Helldar\StrongPassword\ServiceProvider::class);`

**Comment by andrey-helldar** [comment]
Hm...

![image](https://user-images.githubusercontent.com/10347617/123623254-e56d7200-d815-11eb-988f-8a94b6947038.png)

![image](https://user-images.githubusercontent.com/10347617/123623299-ec948000-d815-11eb-8dc0-66542e11ee22.png)

![image](https://user-images.githubusercontent.com/10347617/123623236-e0102780-d815-11eb-9393-4d8371d33ea1.png)

Probably, auto-discover did not work in your application.

You can invoke the command manually:

```bash
composer dumpauto
```

Also check in which block the dependency of the `composer.json` file is connected: `require` or `requre-dev` (`require` needed).

> $this->app->register(\Helldar\StrongPassword\ServiceProvider::class);

Sounds like as Lumen Framework - it does not have auto-discover.
